Т.к мы ищем датасет или бенчмарк, который будет сильно зависеть от retrieval'a, то есть будем придерживаться простого правила, если при замене корпуса в котором ищем факт ответ не изменится, то он нам не подходит, потому что это уже будет проврека general  LLM knowledge и никак не зависит от нашего датасета.

Также стоит обращать свнимание на содержание датасета, мы не может обучать Policy LLM просто на QA без контекста поэтому будем ориентироваться на датасет где есть Q + Evidence/support pessages + A

# FEVER

In [14]:
import json

Для начала был рассмотрен датасет FEVER, данные вряд ли подойдут для последующего GRPO потому что ответы зачастую короткие и на этом вряд ли получится сформировать атомарные гипотезы $(c_1, ... , c_n)$, так же не является классическим вопросно-ответным датасетом (QA), что в последующем сильно усложнит реализацию

In [15]:
DATA_PATH = "../data/FEVER/paper_dev.jsonl"

In [16]:
dataset = [json.loads(sample) for sample in open(DATA_PATH)]

In [17]:
len(dataset)

9999

In [18]:
dataset[0]

{'id': 91198,
 'verifiable': 'NOT VERIFIABLE',
 'label': 'NOT ENOUGH INFO',
 'claim': 'Colin Kaepernick became a starting quarterback during the 49ers 63rd season in the National Football League.',
 'evidence': [[[108548, None, None, None]]]}

# ASQA

In [5]:
import pandas as pd

In [6]:
data = pd.read_parquet("../data/asqa/dev-00000-of-00001-58a9a40c6e69f07b.parquet", engine="pyarrow")

In [7]:
data.head()

,ambiguous_question,qa_pairs,wikipages,annotations,sample_id
0,Who has the highest goals in world football?,"[{'context': 'No context provided', 'question'...",[{'title': 'International Federation of Footba...,"[{'knowledge': [], 'long_answer': 'Ali Dael ha...",-7013890438520559398
1,Who is the original artist of sound of silence?,[{'context': 'Sounds of Silence is the second ...,"[{'title': 'The Sound of Silence', 'url': 'htt...",[{'knowledge': [{'content': 'Wednesday Morning...,7089015503030534342
2,When was the first apple i phone made?,"[{'context': 'On January 9, 2007, Steve Jobs a...","[{'title': 'iPhone (1st generation)', 'url': '...",[{'knowledge': [{'content': 'The iPhone was re...,8793099883447006698
3,Who played the weasley brothers in harry potter?,[{'context': 'Richard Fish appeared as Bill br...,"[{'title': 'List of Harry Potter characters', ...",[{'knowledge': [{'content': 'Dozens of actors ...,-881464876144297194
4,How many state parks are there in virginia?,"[{'context': 'No context provided', 'question'...","[{'title': 'List of Virginia state parks', 'ur...",[{'knowledge': [{'content': 'Virginia opened i...,1650309494326541834

In [8]:
data.iloc[0]["ambiguous_question"]

'Who has the highest goals in world football?'

In [9]:
data.iloc[0]["qa_pairs"]

array([{'context': 'No context provided', 'question': "Who has the highest goals in men's world international football?", 'short_answers': array(['Daei', 'Ali Daei'], dtype=object), 'wikipage': None},
       {'context': 'No context provided', 'question': "Who has the highest goals all-time in men's football?", 'short_answers': array(['Bican', 'Josef Bican'], dtype=object), 'wikipage': None},
       {'context': 'The first player to reach 100 international goals was Italian Elisabetta Vignotto. Abby Wambach scored 100 goals in 9 years, while Christine Sinclair reached the milestone in just under 10 years while Mia Hamm is the youngest player to score 100 international goals at the age of 26 years 185 days. Most played exclusively in the forward position, with Kristine Lilly and Michelle Akers having also played as midfielder. All players scored at a high average rate of more than one goal every three matches. International goals in this list should not include goals scored in penalty-shoot-out; see Penalty shootout (association football). Players who are currently active at international level are indicated in bold type background.', 'question': "Who has the highest goals in women's world international football?", 'short_answers': array(['Sinclair', 'Christine Sinclair'], dtype=object), 'wikipage': "List of women's footballers with 100 or more international goals ..."}],
      dtype=object)

Слабо подходит общие факты и не очень длинные ответы + мало контекста или его вообще нет

# MISUQUE

In [10]:
DATA_PATH = "../data/misuque/musique_ans_v1.0_dev.jsonl"

In [11]:
dataset = [json.loads(sample) for sample in open(DATA_PATH)]

In [12]:
dataset[0]["question"]

'Who is the spouse of the Green performer?'

In [14]:
subsamples = []

In [15]:
for sample in dataset:
    if len(sample["question"]) >= 100:
        subsamples.append(sample)

In [17]:
len(subsamples)

1079

In [21]:
subsamples[0].keys()

dict_keys(['id', 'paragraphs', 'question', 'question_decomposition', 'answer', 'answer_aliases', 'answerable'])

In [25]:
subsamples[0]["answer"]

'Mount Laurel Township'

In [23]:
subsamples[0]["question"]

'What is the place of birth of the person who submitted the first version of the equal rights amendment to congress in 1923?'

In [24]:
subsamples[0]["paragraphs"][:5]

[{'idx': 0,
  'title': 'Equal Rights Amendment',
  'paragraph_text': "Alice Paul, the head of the National Women's Party, believed that the Nineteenth Amendment would not be enough to ensure that men and women were treated equally regardless of sex. In 1923, she revised the proposed amendment to read:",
  'is_supporting': True},
 {'idx': 1,
  'title': 'Twenty-second Amendment to the United States Constitution',
  'paragraph_text': 'The Twenty - second Amendment (Amendment XXII) to the United States Constitution sets a limit on the number of times a person is eligible for election to the office of President of the United States, and also sets additional eligibility conditions for presidents who succeed to the unexpired terms of their predecessors. Congress approved the amendment on March 24, 1947, and submitted it to the state legislatures for ratification. That process was completed on February 27, 1951, after the amendment had been ratified by the requisite 36 of the then - 48 states (as neither Alaska nor Hawaii had yet been admitted as states), and its provisions came into force on that date.',
  'is_supporting': False},
 {'idx': 2,
  'title': 'Article Five of the United States Constitution',
  'paragraph_text': "Article Five of the United States Constitution describes the process whereby the Constitution, the nation's frame of government, may be altered. Altering the Constitution consists of proposing an amendment or amendments and subsequent ratification. Amendments may be proposed either by the Congress with a two - thirds vote in both the House of Representatives and the Senate or by a convention of states called for by two - thirds of the state legislatures. To become part of the Constitution, an amendment must be ratified by either -- as determined by Congress -- the legislatures of three - quarters of the states or state ratifying conventions in three - quarters of the states. The vote of each state (to either ratify or reject a proposed amendment) carries equal weight, regardless of a state's population or length of time in the Union.",
  'is_supporting': False},
 {'idx': 3,
  'title': 'Fundamental rights in India',
  'paragraph_text': "Fundamental Rights are the basic rights of the people and inalienable rights of the people who enjoys it the charter of rights contained in Part III (Article 12 to 35) of Constitution of India. It guarantees civil liberties such that all Indians can lead their lives in peace and harmony as citizens of India. These include individual rights common to most liberal democracies, such as equality before law freedom of speech and expression, religious and cultural freedom and peaceful assembly, freedom to practice religion, and the right to constitutional remedies for the protection of civil rights by means of writs such as habeas corpus, Mandamus, Prohibition, Certiorari and Quo Warranto. Violation of these rights result in punishments as prescribed in the Indian Penal Code or other special laws, subject to discretion of the judiciary. The Fundamental Rights are defined as basic human freedoms that every Indian citizen has the right to enjoy for a proper and harmonious development of personality. These rights universally apply to all citizens, irrespective of race, place of birth, religion, caste or gender. Though the rights conferred by the constitution other than fundamental rights are equally valid and their enforcement in case of violation shall be secured from the judiciary in a time consuming legal process. However, in case of fundamental rights violation, Supreme court of India can be approached directly for ultimate justice per Article 32. The Rights have their origins in many sources, including England's Bill of Rights, the United States Bill of Rights and France's Declaration of the Rights of Man.",
  'is_supporting': False},
 {'idx': 4,
  'title': 'United States Bill of Rights',
  'paragraph_text': "The Bill of Rights in the United States is the first ten amendments to the United States Constitution. Proposed following the often bitter 1787 -- 88 debate over ratification of the U.S. Constitution, and written to address the objections raised by Anti-Federalists, the Bill of Rights amendments add to the Constitution specific guarantees of personal freedoms and rights, clear limitations on the government's power in judicial and other proceedings, and explicit declarations that all powers not specifically delegated to Congress by the Constitution are reserved for the states or the people. The concepts codified in these amendments are built upon those found in several earlier documents, including the Virginia Declaration of Rights and the English Bill of Rights, along with earlier documents such as Magna Carta (1215). In practice, the amendments had little impact on judgments by the courts for the first 150 years after ratification.",
  'is_supporting': False}]

In [27]:
subsamples[0]

{'id': '2hop__61318_362941',
 'paragraphs': [{'idx': 0,
   'title': 'Equal Rights Amendment',
   'paragraph_text': "Alice Paul, the head of the National Women's Party, believed that the Nineteenth Amendment would not be enough to ensure that men and women were treated equally regardless of sex. In 1923, she revised the proposed amendment to read:",
   'is_supporting': True},
  {'idx': 1,
   'title': 'Twenty-second Amendment to the United States Constitution',
   'paragraph_text': 'The Twenty - second Amendment (Amendment XXII) to the United States Constitution sets a limit on the number of times a person is eligible for election to the office of President of the United States, and also sets additional eligibility conditions for presidents who succeed to the unexpired terms of their predecessors. Congress approved the amendment on March 24, 1947, and submitted it to the state legislatures for ratification. That process was completed on February 27, 1951, after the amendment had been ratified by the requisite 36 of the then - 48 states (as neither Alaska nor Hawaii had yet been admitted as states), and its provisions came into force on that date.',
   'is_supporting': False},
  {'idx': 2,
   'title': 'Article Five of the United States Constitution',
   'paragraph_text': "Article Five of the United States Constitution describes the process whereby the Constitution, the nation's frame of government, may be altered. Altering the Constitution consists of proposing an amendment or amendments and subsequent ratification. Amendments may be proposed either by the Congress with a two - thirds vote in both the House of Representatives and the Senate or by a convention of states called for by two - thirds of the state legislatures. To become part of the Constitution, an amendment must be ratified by either -- as determined by Congress -- the legislatures of three - quarters of the states or state ratifying conventions in three - quarters of the states. The vote of each state (to either ratify or reject a proposed amendment) carries equal weight, regardless of a state's population or length of time in the Union.",
   'is_supporting': False},
  {'idx': 3,
   'title': 'Fundamental rights in India',
   'paragraph_text': "Fundamental Rights are the basic rights of the people and inalienable rights of the people who enjoys it the charter of rights contained in Part III (Article 12 to 35) of Constitution of India. It guarantees civil liberties such that all Indians can lead their lives in peace and harmony as citizens of India. These include individual rights common to most liberal democracies, such as equality before law freedom of speech and expression, religious and cultural freedom and peaceful assembly, freedom to practice religion, and the right to constitutional remedies for the protection of civil rights by means of writs such as habeas corpus, Mandamus, Prohibition, Certiorari and Quo Warranto. Violation of these rights result in punishments as prescribed in the Indian Penal Code or other special laws, subject to discretion of the judiciary. The Fundamental Rights are defined as basic human freedoms that every Indian citizen has the right to enjoy for a proper and harmonious development of personality. These rights universally apply to all citizens, irrespective of race, place of birth, religion, caste or gender. Though the rights conferred by the constitution other than fundamental rights are equally valid and their enforcement in case of violation shall be secured from the judiciary in a time consuming legal process. However, in case of fundamental rights violation, Supreme court of India can be approached directly for ultimate justice per Article 32. The Rights have their origins in many sources, including England's Bill of Rights, the United States Bill of Rights and France's Declaration of the Rights of Man.",
   'is_supporting': False},
  {'idx': 4,
   'title': 'United States Bill of Rights',
   'paragraph_text': "The Bill of Rights in the United States is the first ten amendments to the United States Constitution. Proposed following the often bitter 1787 -- 88 debate over ratification of the U.S. Constitution, and written to address the objections raised by Anti-Federalists, the Bill of Rights amendments add to the Constitution specific guarantees of personal freedoms and rights, clear limitations on the government's power in judicial and other proceedings, and explicit declarations that all powers not specifically delegated to Congress by the Constitution are reserved for the states or the people. The concepts codified in these amendments are built upon those found in several earlier documents, including the Virginia Declaration of Rights and the English Bill of Rights, along with earlier documents such as Magna Carta (1215). In practice, the amendments had little impact on judgments by the courts for the first 150 years after ratification.",
   'is_supporting': False},
  {'idx': 5,
   'title': 'Nineteenth Amendment to the United States Constitution',
   'paragraph_text': "The Nineteenth Amendment was originally introduced in Congress in 1878 by Senator Aaron A. Sargent. Forty - one years later, in 1919, Congress submitted it to the states for ratification. It was ratified by three - fourths of the states a year later, with Tennessee's ratification being the last needed to add the amendment to the Constitution. In Leser v. Garnett (1922), the Supreme Court rejected claims that the amendment was unconstitutionally adopted.",
   'is_supporting': False},
  {'idx': 6,
   'title': 'History of the United States Constitution',
   'paragraph_text': 'The drafted Constitution was submitted to the Confederation Congress. It in turn forwarded the Constitution as drafted to the states for ratification by the Constitutional method proposed. The Federalist Papers provided background and justification for the Constitution. Some states agreed to ratify the Constitution only if the amendments that were to become the Bill of Rights would be taken up immediately by the new government, and they were duly proposed in the first session of the First Congress.',
   'is_supporting': False},
  {'idx': 7,
   'title': 'Constitution of the United States',
   'paragraph_text': 'Since the Constitution came into force in 1789, it has been amended 27 times, including an amendment to repeal a previous one, in order to meet the changing needs of a nation that has profoundly changed since the eighteenth century. In general, the first ten amendments, known collectively as the Bill of Rights, offer specific protections of individual liberty and justice and place restrictions on the powers of government. The majority of the seventeen later amendments expand individual civil rights protections. Others address issues related to federal authority or modify government processes and procedures. Amendments to the United States Constitution, unlike ones made to many constitutions worldwide, are appended to the document. All four pages of the original U.S. Constitution are written on parchment.',
   'is_supporting': False},
  {'idx': 8,
   'title': 'Fundamental rights in India',
   'paragraph_text': "Fundamental Rights are the basic rights of the common people and inalienable rights of the people who enjoy it under the charter of rights contained in Part III (Article 12 to 35) of Constitution of India. It guarantees civil liberties such that all Indians can lead their lives in peace and harmony as citizens of India. These include individual rights common to most liberal democracies, such as equality before law, freedom of speech and expression, religious and cultural freedom and peaceful assembly, freedom to practice religion, and the right to constitutional remedies for the protection of civil rights by means of writs such as habeas corpus, Mandamus, Prohibition, Certiorari and Quo Warranto. Violation of these rights result in punishments as prescribed in the Indian Penal Code or other special laws, subject to discretion of the judiciary. The Fundamental Rights are defined as basic human freedoms that every Indian citizen has the right to enjoy for a proper and harmonious development of personality. These rights universally apply to all citizens, irrespective of race, place of birth, religion, caste or gender. Though the rights conferred by the constitution other than fundamental rights are equally valid and their enforcement in case of violation shall be secured from the judiciary in a time consuming legal process. However, in case of fundamental rights violation, the Supreme Court of India can be approached directly for ultimate justice per Article 32. The Rights have their origins in many sources, including England's Bill of Rights, the United States Bill of Rights and France's Declaration of the Rights of Man.",
   'is_supporting': False},
  {'idx': 9,
   'title': 'Twenty-sixth Amendment to the United States Constitution',
   'paragraph_text': 'On March 23, 1971, a proposal to lower the voting age to 18 years was adopted by both houses of Congress and sent to the states for ratification. The amendment became part of the Constitution on July 1, 1971, three months and eight days after the amendment was submitted to the states for ratification, making this amendment the quickest to be ratified.',
   'is_supporting': False},
  {'idx': 10,
   'title': 'Twenty-third Amendment to the United States Constitution',
   'paragraph_text': 'The Twenty - third Amendment (Amendment XXIII) to the United States Constitution extends the right to vote in the presidential election to citizens residing in the District of Columbia by granting the District electors in the Electoral College, as if it was a state. The amendment was proposed by the 86th Congress on June 16, 1960. Ratification by the requisite 38 of the 50 states was completed on March 29, 1961.',
   'is_supporting': False},
  {'idx': 11,
   'title': 'United States Bill of Rights',
   'paragraph_text': "On June 8, 1789, Representative James Madison introduced nine amendments to the Constitution in the House of Representatives. Among his recommendations Madison proposed opening up the Constitution and inserting specific rights limiting the power of Congress in Article One, Section 9. Seven of these limitations would become part of the ten ratified Bill of Rights amendments. Ultimately, on September 25, 1789, Congress approved twelve articles of amendment to the Constitution, each consisting of one one - sentence paragraph, and submitted them to the states for ratification. Contrary to Madison's original proposal that the articles be incorporated into the main body of the Constitution, they were proposed as supplemental additions (codicils) to it. Articles Three through Twelve were ratified as additions to the Constitution on December 15, 1791, and became Amendments One through Ten of the Constitution. Article Two became part of the Constitution on May 5, 1992, as the Twenty - seventh Amendment. Article One is technically still pending before the states.",
   'is_supporting': False},
  {'idx': 12,
   'title': 'Second Amendment to the United States Constitution',
   'paragraph_text': 'The Second Amendment (Amendment II) to the United States Constitution protects the right of the people to keep and bear arms and was adopted on December 15, 1791, as part of the first ten amendments contained in the Bill of Rights. The Supreme Court of the United States has ruled that the right belongs to individuals for self defense. while also ruling that the right is not unlimited and does not prohibit all regulation of either firearms or similar devices. State and local governments are limited to the same extent as the federal government from infringing this right, per the incorporation of the Bill of Rights.',
   'is_supporting': False},
  {'idx': 13,
   'title': '51st state',
   'paragraph_text': 'This position was carried by the D.C. Statehood Party, a political party; it has since merged with the local Green Party affiliate to form the D.C. Statehood Green Party. The nearest this movement ever came to success was in 1978, when Congress passed the District of Columbia Voting Rights Amendment. Two years later in 1980, local citizens passed an initiative calling for a constitutional convention for a new state. In 1982, voters ratified the constitution of the state, which was to be called New Columbia. The drive for statehood stalled in 1985, however, when the Washington, D.C. Voting Rights Amendment failed because not enough states ratified the amendment within the seven-year span specified.',
   'is_supporting': False},
  {'idx': 14,
   'title': 'Second Amendment to the United States Constitution',
   'paragraph_text': 'The Second Amendment (Amendment II) to the United States Constitution protects the right of the people to keep and bear arms and was adopted on December 15, 1791, as part of the first ten amendments contained in the Bill of Rights. The Supreme Court of the United States has ruled that the right belongs to individuals, while also ruling that the right is not unlimited and does not prohibit all regulation of either firearms or similar devices. State and local governments are limited to the same extent as the federal government from infringing this right, per the incorporation of the Bill of Rights.',
   'is_supporting': False},
  {'idx': 15,
   'title': 'Pledge of Allegiance',
   'paragraph_text': "In 1923, the National Flag Conference called for the words ``my Flag ''to be changed to`` the Flag of the United States,'' so that new immigrants would not confuse loyalties between their birth countries and the US. The words ``of America ''were added a year later. Congress officially recognized the Pledge for the first time, in the following form, on June 22, 1942:",
   'is_supporting': False},
  {'idx': 16,
   'title': 'APA Ethics Code',
   'paragraph_text': 'The first version was published by the APA in 1953. The need for such a document came after psychologists were taking on more professional and public roles post-World War II. A committee was developed and reviewed situations submitted by psychologists in the field who felt they had encountered ethical dilemmas. The committee organized these situations into themes and included them in the first document which was 170 pages in length. Over the years, a distinction was made between aspirational principles and enforceable standards. Since, there have been nine revisions with the most recent published in 2002 and amended in 2010.',
   'is_supporting': False},
  {'idx': 17,
   'title': 'First Amendment to the United States Constitution',
   'paragraph_text': 'The First Amendment (Amendment I) to the United States Constitution prevents Congress from making any law respecting an establishment of religion, prohibiting the free exercise of religion, or abridging the freedom of speech, the freedom of the press, the right to peaceably assemble, or to petition for a governmental redress of grievances. It was adopted on December 15, 1791, as one of the ten amendments that constitute the Bill of Rights.',
   'is_supporting': False},
  {'idx': 18,
   'title': 'Paulsdale',
   'paragraph_text': "Paulsdale, in Mount Laurel Township, New Jersey, was the birthplace and childhood home of Alice Paul, a major leader in the Women's suffrage movement in the United States. Paulsdale was designated a National Historic Landmark in 1991.",
   'is_supporting': True},
  {'idx': 19,
   'title': 'Fundamental rights in India',
   'paragraph_text': "``Fundamental Rights ''are the basic rights of the common people and inalienable rights of the people who enjoy it under the charter of rights contained in Part III (Article 12 to 35) of Constitution of India. It guarantees civil liberties such that all Indians can lead their lives in peace and harmony as citizens of India. These include individual rights common to most liberal democracies, such as equality before law freedom of speech and expression, religious and cultural freedom and peaceful assembly, freedom to practice religion, and the right to constitutional remedies for the protection of civil rights by means of writs such as habeas corpus, Mandamus, Prohibition, Certiorari and Quo Warranto. Violation of these rights result in punishments as prescribed in the Indian Penal Code or other special laws, subject to discretion of the judiciary. The Fundamental Rights are defined as basic human freedoms that every Indian citizen has the right to enjoy for a proper and harmonious development of personality. These rights universally apply to all citizens, irrespective of race, place of birth, religion, caste or gender. Though the rights conferred by the constitution other than fundamental rights are equally valid and their enforcement in case of violation shall be secured from the judiciary in a time consuming legal process. However, in case of fundamental rights violation, Supreme court of India can be approached directly for ultimate justice per Article 32. The Rights have their origins in many sources, including England's Bill of Rights, the United States Bill of Rights and France's Declaration of the Rights of Man.",
   'is_supporting': False}],
 'question': 'What is the place of birth of the person who submitted the first version of the equal rights amendment to congress in 1923?',
 'question_decomposition': [{'id': 61318,
   'question': 'who submitted the first version of the equal rights amendment to congress in 1923',
   'answer': 'Alice Paul',
   'paragraph_support_idx': 0},
  {'id': 362941,
   'question': '#1 >> place of birth',
   'answer': 'Mount Laurel Township',
   'paragraph_support_idx': 18}],
 'answer': 'Mount Laurel Township',
 'answer_aliases': [],
 'answerable': True}

Выводы по данному датасету:

[+] Нельзя ответить по 1 фатку  \
[+] Есть доказательства \
[+] Подходит для retrieval'a \
[x] Не подойдет для Falsification

# QASPER

In [1]:
import pandas as pd

In [2]:
dataset = pd.read_parquet("../data/Qasper/0000.parquet")

In [4]:
dataset.head()

,id,title,abstract,full_text,qas,figures_and_tables
0,1911.10742,End-to-End Trainable Non-Collaborative Dialog ...,End-to-end task-oriented dialog models have ac...,"{'section_name': ['Introduction', 'Related Wor...",{'question': ['How big is the ANTISCAM dataset...,{'caption': ['Table 1: Hierarchical intent ann...
1,1904.09131,OpenTapioca: Lightweight Entity Linking for Wi...,We propose a simple Named Entity Linking syste...,"{'section_name': ['Introduction', 'Particulari...",{'question': ['What is the accuracy of this mo...,{'caption': ['Figure 1: Example of an annotate...
2,1611.06322,Spotting Rumors via Novelty Detection,Rumour detection is hard because the most accu...,"{'section_name': ['Introduction', 'Related Wor...",{'question': ['What previous methods do they c...,{'caption': ['Table 1: Excerpt of topics with ...
3,1604.02038,Sentence Level Recurrent Topic Model: Letting ...,We propose Sentence Level Recurrent Topic Mode...,"{'section_name': ['Introduction', 'Related Wor...",{'question': ['What baselines did they compare...,{'caption': ['Figure 1: The illustration of th...
4,1911.04474,TENER: Adapting Transformer Encoder for Named ...,The Bidirectional long short-term memory netwo...,"{'section_name': ['Introduction', 'Related Wor...",{'question': ['Which NER dataset do they use?'...,{'caption': ['Figure 1: An example for NER. Th...

In [10]:
dataset.iloc[0]["qas"]["question"]

array(['How big is the ANTISCAM dataset? ', 'How is intent annotated?',
       'What are the baselines outperformed by this work?',
       'What are the evaluation metrics and criteria used to evaluate the model performance?'],
      dtype=object)

In [13]:
dataset.iloc[0]["full_text"]

{'section_name': array(['Introduction', 'Related Work',
        'Non-Collaborative Task Annotation Scheme', 'Datasets',
        'Datasets ::: AntiScam Dataset',
        'Datasets ::: PersuasionForGood Dataset', 'Model ::: Background',
        'Model ::: Intent and Semantic Slot Classifiers',
        'Model ::: Response Generation', 'Model ::: Response Filtering',
        'Experiments', 'Experiments ::: Baseline Models',
        'Experiments ::: Automatic Evaluation Metrics',
        'Experiments ::: Human Evaluation Metrics', 'Results and Analysis',
        'Conclusion and Future Work', 'Acknowledgements',
        'Appendix ::: Anti-Scam Collection Setting',
        'Appendix ::: Training details', 'Appendix ::: Example Dialog'],
       dtype=object),
 'paragraphs': array([array(['Considerable progress has been made building end-to-end dialog systems for collaborative tasks in which users cooperate with the system to achieve a common goal. Examples of collaborative tasks include making restaurant reservations and retrieving bus time-table information. Since users typically have clear and explicit intentions in collaborative tasks, existing systems commonly classify user utterances into pre-defined intents. In contrast, non-collaborative tasks are those where the users and the system do not strive to achieve the same goal. Examples of such tasks include deceiving attackers, persuading users to donate to a cause BIBREF1, and negotiating a product price BIBREF2, BIBREF3. In these tasks, users often perform complex actions that are beyond a simple set of pre-defined intents. In order to reach a common state, the user and the system need to build rapport and trust which naturally involves off-task content. Previous work did not model off-task content BIBREF2, which may have led to less optimal results. For example, in the persuasion task BIBREF1, users would ask the system “How do you feel about war?" An example of an on-task system response that the system could have made is “Do you want to make a donation?", which sticks to the task but neglects users\' question. However, a better response to such an off-task question is “War is destructive and pitiless, but you can donate to help child victims of war." This response is better, as it has been found that users are more likely to end the conversation if the system neglects their questions BIBREF4. Therefore, we need to design a system that handles both on-task and off-task information appropriately and in a way that leads back to the system\'s goal.',
               'To tackle the issue of incoherent system responses to off-task content, previous studies have built hybrid systems to interleave off-task and on-task content. BIBREF4 used a rule-based dialog manager for on-task content and a neural model for off-task content, and trained a reinforcement learning model to select between these two models based on the dialog context. However, such a method is difficult to train and struggles to generalize beyond the movie promotion task they considered. To tackle these problems, we propose a hierarchical intent annotation scheme that separates on-task and off-task information in order to provide detailed supervision. For on-task information, we directly use task-related intents for representation. Off-task information, on the other hand, is too general to categorize into specific intents, so we choose dialog acts that convey syntax information. These acts, such as “open question" are general to all tasks.',
               "Previous studies use template-based methods to maintain sentence coherence. However, rigid templates lead to limited diversity, causing the user losing engagement. On the other hand, language generation models can generate diverse responses but are bad at being coherent. We propose Multiple Intents and Semantic Slots Annotation Neural Network (MISSA) to combine the advantages of both template and generation models and takes advantage from the hierarchical annotation at the same time. MISSA follows the TransferTransfo framework BIBREF0 with three modifications: (i) We first concurrently predict user's, system's intents and semantic slots; (ii) We then perform conditional generation to improve generated response's coherence. Specifically, we generate responses conditioned on the above intermediate representation (intents and slots); (iii) Finally, we generate multiple responses with the nucleus sampling strategy BIBREF5 and then apply a response filter, which contains a set of pre-defined constraints to select coherent responses. The constraints in the filter can be defined according to specific task requirements or general conversational rules.",
               'To enrich publicly available non-collaborative task datasets, we collect a new dataset AntiScam, where users defend themselves against attackers trying to collect personal information. As non-collaborative tasks are still relatively new to the study of dialog systems, there are insufficiently many meaningful datasets for evaluation and we hope this provides a valuable example. We evaluate MISSA on the newly collected AntiScam dataset and an existing PersuasionForGood dataset. Both automatic and human evaluations suggest that MISSA outperforms multiple competitive baselines.',
               "In summary, our contributions include: (i) We design a hierarchical intent annotation scheme and a semantic slot annotation scheme to annotate the non-collaborative dialog dataset, we also propose a carefully-designed AntiScam dataset to facilitate the research of non-collaborative dialog systems. (ii) We propose a model that can be applied to all non-collaborative tasks, outperforming other baselines on two different non-collaborative tasks. (iii) We develop an anti-scam dialog system to occupy attacker's attention and elicit their private information for social good. Furthermore, we also build a persuasion dialog system to persuade people to donate to charities. We release the code and data."],
              dtype=object)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ,
        array(['The interest in non-collaborative tasks has been increasing and there have already been several related datasets. For instance, BIBREF1 wang2019persuasion collected conversations where one participant persuades another to donate to a charity. BIBREF2 he2018decoupling collected negotiation dialogs where buyers and sellers bargain for items for sale on Craigslist. There are many other non-collaborative tasks, such as the turn-taking game BIBREF6, the multi-party game BIBREF7 and item splitting negotiation BIBREF8. Similar to the AntiScam dataset proposed in this paper, these datasets contain off-task content and can be used to train non-collaborative dialog systems. However, since they are not specifically collected and designed for non-collaborative tasks, it might be difficult to disentangle the on-task and off-task contents and measure the performance. Therefore, we propose the AntiScam dataset, which is designed to interleave the on-task and off-task contents in the conversation, and can serve as a benchmark dataset for similar non-collaborative tasks.',
               'To better understand user utterances and separate on-task and off-task content within a conversation, previous work has designed hierarchical annotation schemes for specific domains. BIBREF9 hardy2002multi followed the DAMSL schemeBIBREF10 and annotated a multilingual human-computer dialog corpus with a hierarchical dialog act annotation scheme. BIBREF11 gupta2018semantic used a hierarchical annotation scheme for semantic parsing. Inspired by these studies, our idea is to annotate the intent and semantic slot separately in non-collaborative tasks. We propose a hierarchical intent annotation scheme that can be adopted by all non-collaborative tasks. With this annotation scheme, MISSA is able to quickly build an end-to-end trainable dialog system for any non-collaborative task.',
               'Traditional task-oriented dialog systems BIBREF12 are usually composed of multiple independent modules, for example, natural language understanding, dialog state tracking BIBREF13, BIBREF14, dialog policy manager BIBREF15, and natural language generation BIBREF16. Conversational intent is adopted to capture the meaning of task content in these dialog systems BIBREF2, BIBREF17. In comparison to this work, we use a hierarchical intent scheme that includes off-task and on-task intents to capture utterance meaning. We also train the model in a multi-task fashion to predict decoupled intents and semantic slots. The major defect of a separately trained pipeline is the laborious dialog state design and annotation. In order to mitigate this problem, recent work has explored replacing independent modules with end-to-end neural networks BIBREF18, BIBREF19, BIBREF20. Our model also follows this end-to-end fashion.',
               'Over the last few years, we have witnessed a huge growth in non-task-oriented dialog systems BIBREF21, BIBREF22. Social chatbots such as Gunrock BIBREF23 were able to maintain a conversation for around ten minutes in an open domain. Recent improvements build on top of the transformer and pre-trained language models BIBREF24, BIBREF25, BIBREF26, obtained state-of-the-art results on the Persona-Chat dataset BIBREF0. Pre-trained language models are proposed to build task-oriented dialog systems to drive the progress on leveraging large amounts of available unannotated data. BIBREF27. Similarly, our approach is also built on top of the TransferTransfo framework BIBREF0. BIBREF27 budzianowski2019hello focused on collaborative tasks BIBREF28. We target non-collaborative tasks instead.',
               'Another line of work interleaves on-task and off-task content by building a hybrid dialog system that combines a task-oriented model and a non-task-oriented model BIBREF4, BIBREF29. In these studies, task-oriented systems and non-task-oriented systems are designed separately and both systems generate candidate responses. A selector is then designed to choose an appropriate output from the candidate responses BIBREF4 and a connector to combine two response candidates BIBREF30, BIBREF31. Compared with these works, MISSA is end-to-end trainable and thus easier to train and update.'],
              dtype=object)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ,
        array(["To decouple syntactic and semantic information in utterances and provide detailed supervision, we design a hierarchical intent annotation scheme for non-collaborative tasks. We first separate on-task and off-task intents. As on-task intents are key actions that can vary among different tasks, we need to specifically define on-task intents for each task. On the other hand, since off-task content is too general to design task-specific intents, we choose common dialog acts as the categories. The advantage of this hierarchical annotation scheme is apparent when starting a new non-collaborative task: we only need to focus on designing the on-task categories and semantic slots which are the same as traditional task-oriented dialog systems. Consequently, we don't have to worry about the off-task annotation design since the off-task category is universal.",
               'In the intent annotation scheme shown in Table TABREF2, we list the designed intent annotation scheme for the newly collected AntiScam dataset and the PersuasionForGood dataset. We first define on-task intents for the datasets, which are key actions in the task. Since our AntiScam focuses on understanding and reacting towards elicitations, we define elicitation, providing_information and refusal as on-task intents. In the PersuasionForGood dataset, we define nine on-task intents in Table TABREF2 based on the original PersuasionForGood dialog act annotation scheme. All these intents are related to donation actions, which are salient on-task intents in the persuasion task. The off-task intents are the same for both tasks, including six general intents and six additional social intents. General intents are more closely related to the syntactic meaning of the sentence (open_question, yes_no_question, positive_answer, negative_answer, responsive_statement, and nonresponsive_statement) while social intents are common social actions (greeting, closing, apology, thanking,respond_to_thank, and hold).',
               'For specific tasks, we also design a semantic slot annotation scheme for annotating sentences based on their semantic content. We identify 13 main semantic slots in the anti-scam task, for example, credit card numbers. We present a detailed semantic slot annotation in Table TABREF3. Following BIBREF1, we segment each conversation turn into single sentences and then annotate each sentence rather than turns.'],
              dtype=object)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ,
        array(['We test our approach on two non-collaborative task datasets: the AntiScam dataset and the PersuasionForGood dataset BIBREF1. Both datasets are collected from the Amazon Mechanical Turk platform in the form of typing conversations and off-task dialog is interleaved in the dialog.'],
              dtype=object)                                                                                                                                                                                                                                                                               ,
        array(['To enrich available non-collaborative task datasets, we created a corpus of human-human anti-scam dialogs in order to learn human elicitation strategies. We chose a popular Amazon customer service scam scenario to collect dialogs between users and attackers who aim to collect users information. We posted a role-playing task on the Amazon Mechanical Turk platform and collected a typing conversation dataset named AntiScam. We collected 220 human-human dialogs. The average conversation length is 12.45 turns and the average utterance length is 11.13 words. Only 172 out of 220 users successfully identified their partner as an attacker, suggesting that the attackers are well trained and not too easily identifiable. We recruited two expert annotators who have linguistic training to annotate 3,044 sentences in 100 dialogs, achieving a 0.874 averaged weighted kappa value.'],
              dtype=object)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ,
        array(['The PersuasionForGood dataset BIBREF1 was collected from typing conversations on Amazon Mechanical Turk platform. Two workers were randomly paired, one was assigned the role of persuader, the other was persuadee. The goal of the persuader was to persuade the persuadee to donate a portion of task earning to a specific charity. The dataset consists of 1,017 dialogs, where 300 dialogs are annotated with dialog acts. The average conversation length is 10.43, the vocabulary size is 8,141. Since the original PersuasionForGood dataset is annotated with dialog acts, we select the on-task dialog acts as on-task intents shown in Table TABREF2, and categorize the other dialog acts into our pre-defined off-task intents.'],

Что-то уже подходящее, подходит под RAG можно искаль false evidence и ответы/вопросы однозначно сильно полагаются на данные статей в датасете